version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stop-rds-instances"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n7lsnx0djkm3"
s3_prefix = "stop-rds-instances"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
